import logo1 from "../src/assets/logo/logo1.png";
import logo0 from "../src/assets/logo/logo0.png";
import call from "../src/assets/icons/call.png";
import mail from "../src/assets/icons/mail.png";
import map from "../src/assets/icons/map.png";
import facebook from "../src/assets/icons/facebook.svg";
import instagram from "../src/assets/icons/instagram.svg";
import x from "../src/assets/icons/x.svg";
import svg1 from "../src/assets/icons/svg-1.svg";
import svg2 from "../src/assets/icons/svg-2.svg";
import svg3 from "../src/assets/icons/svg-3.svg";
import svg4 from "../src/assets/icons/svg-4.svg";

export const brandLogo = logo1;
export const brandLogo2 = logo0;
export const callIcon = call;
export const mailIcon = mail;
export const mapIcon = map;
export const facebookSVG = facebook;
export const instagramSVG = instagram;
export const xSVG = x;
export const squareSVG = svg1;
export const circleSVG = svg2;
export const cross1SVG = svg3;
export const cross2SVG = svg4;
